import React, { useState } from 'react'
import { MessageSquare, Wand2, Copy, Check } from 'lucide-react'
import { draftResponse } from '../api/aiApi'

interface AiDraftCardProps {
    requestId: number
    onUseDraft?: (draft: string) => void
}

const AiDraftCard: React.FC<AiDraftCardProps> = ({ requestId, onUseDraft }) => {
    const [draft, setDraft] = useState<string | null>(null)
    const [isLoading, setIsLoading] = useState(false)
    const [error, setError] = useState<string | null>(null)
    const [metaInfo, setMetaInfo] = useState<string | null>(null)
    const [copied, setCopied] = useState(false)
    const [promptOverride, setPromptOverride] = useState('')

    const handleDraft = async () => {
        setIsLoading(true)
        setError(null)
        setCopied(false)
        try {
            const data = await draftResponse(requestId, { promptOverride: promptOverride || undefined })
            setDraft(data.draft)
            setMetaInfo(`Generated by ${data.provider} (${data.model}) in ${data.latencyMs}ms`)
        } catch (err: unknown) {
            const message = (err as { response?: { data?: { message?: string } } })?.response?.data?.message
            setError(message || 'Failed to generate draft.')
        } finally {
            setIsLoading(false)
        }
    }

    const copyToClipboard = () => {
        if (!draft) return
        navigator.clipboard.writeText(draft)
        setCopied(true)
        setTimeout(() => setCopied(false), 2000)
    }

    return (
        <div style={{ backgroundColor: 'var(--color-bg)', padding: 16, borderRadius: 6 }}>
            <div className="flex items-center justify-between mb-3">
                <div className="flex items-center gap-2 font-medium text-sm">
                    <MessageSquare size={14} color="var(--color-primary)" />
                    Response Drafter
                </div>
            </div>

            {error && <div className="alert alert-error text-sm" style={{ padding: 8, marginBottom: 12 }}>{error}</div>}

            <div style={{ marginBottom: 12 }}>
                <input
                    type="text"
                    className="form-input"
                    placeholder="Optional instructions (e.g. 'Ask for device logs')"
                    value={promptOverride}
                    onChange={(e) => setPromptOverride(e.target.value)}
                    disabled={isLoading}
                    style={{ fontSize: 13, padding: '6px 10px' }}
                />
            </div>

            {!draft && (
                <button
                    className="btn btn-primary"
                    style={{ padding: '6px 12px', fontSize: 13, width: '100%', justifyContent: 'center' }}
                    onClick={handleDraft}
                    disabled={isLoading}
                >
                    {isLoading ? 'Drafting...' : <><Wand2 size={14} /> Generate Draft</>}
                </button>
            )}

            {draft && (
                <div>
                    <div style={{ position: 'relative' }}>
                        <textarea
                            value={draft}
                            onChange={(e) => setDraft(e.target.value)}
                            style={{
                                width: '100%',
                                minHeight: 120,
                                padding: 12,
                                backgroundColor: 'var(--color-surface-2)',
                                border: '1px solid var(--color-border)',
                                borderRadius: 4,
                                fontSize: 13,
                                color: 'var(--color-text)',
                                lineHeight: 1.6,
                                resize: 'vertical'
                            }}
                        />
                        <button
                            onClick={copyToClipboard}
                            title="Copy to clipboard"
                            style={{ position: 'absolute', top: 8, right: 8, padding: 4, background: 'var(--color-bg)', border: '1px solid var(--color-border)', borderRadius: 4, cursor: 'pointer', color: 'var(--color-text-muted)' }}
                        >
                            {copied ? <Check size={14} color="green" /> : <Copy size={14} />}
                        </button>
                    </div>

                    <div className="flex items-center justify-between mt-3">
                        <span className="text-muted text-xs">{metaInfo}</span>
                        <div className="flex gap-2">
                            <button
                                className="btn btn-secondary"
                                style={{ padding: '4px 10px', fontSize: 12 }}
                                onClick={handleDraft}
                                disabled={isLoading}
                            >
                                {isLoading ? 'Retry...' : 'Regenerate'}
                            </button>
                            {onUseDraft && (
                                <button
                                    className="btn btn-primary"
                                    style={{ padding: '4px 10px', fontSize: 12 }}
                                    onClick={() => {
                                        onUseDraft(draft)
                                        setTimeout(() => {
                                            const el = document.getElementById('comment-body')
                                            if (el) {
                                                el.focus()
                                                el.scrollIntoView({ behavior: 'smooth', block: 'center' })
                                            }
                                        }, 100)
                                    }}
                                >
                                    Use Draft
                                </button>
                            )}
                        </div>
                    </div>
                </div>
            )}
        </div>
    )
}

export default AiDraftCard
