import React, { useState } from 'react'
import { FileText, Wand2 } from 'lucide-react'
import { summarizeRequest } from '../api/aiApi'

interface AiSummaryCardProps {
    requestId: number
}

const AiSummaryCard: React.FC<AiSummaryCardProps> = ({ requestId }) => {
    const [summary, setSummary] = useState<string | null>(null)
    const [isLoading, setIsLoading] = useState(false)
    const [error, setError] = useState<string | null>(null)
    const [metaInfo, setMetaInfo] = useState<string | null>(null)

    const handleSummarize = async () => {
        setIsLoading(true)
        setError(null)
        try {
            const data = await summarizeRequest(requestId)
            setSummary(data.summary)
            setMetaInfo(`Generated by ${data.provider} (${data.model}) in ${data.latencyMs}ms`)
        } catch (err: unknown) {
            const message = (err as { response?: { data?: { message?: string } } })?.response?.data?.message
            setError(message || 'Failed to generate summary.')
        } finally {
            setIsLoading(false)
        }
    }

    return (
        <div style={{ backgroundColor: 'var(--color-bg)', padding: 16, borderRadius: 6 }}>
            <div className="flex items-center justify-between mb-2">
                <div className="flex items-center gap-2 font-medium text-sm">
                    <FileText size={14} color="var(--color-primary)" />
                    Request Summary
                </div>
                {!summary && (
                    <button
                        className="btn btn-primary"
                        style={{ padding: '4px 10px', fontSize: 12 }}
                        onClick={handleSummarize}
                        disabled={isLoading}
                    >
                        {isLoading ? 'Summarizing...' : <><Wand2 size={12} /> Generate</>}
                    </button>
                )}
            </div>

            {error && <div className="alert alert-error text-sm" style={{ padding: 8 }}>{error}</div>}

            {summary && (
                <div>
                    <div style={{ padding: 12, backgroundColor: 'var(--color-surface-2)', border: '1px solid var(--color-border)', borderRadius: 4, whiteSpace: 'pre-wrap', fontSize: 13, lineHeight: 1.6 }}>
                        {summary}
                    </div>

                    <div className="flex items-center justify-between mt-3">
                        <span className="text-muted text-xs">{metaInfo}</span>
                        <button
                            className="btn btn-secondary"
                            style={{ padding: '4px 10px', fontSize: 12 }}
                            onClick={handleSummarize}
                            disabled={isLoading}
                        >
                            {isLoading ? 'Retry...' : 'Regenerate'}
                        </button>
                    </div>
                </div>
            )}
        </div>
    )
}

export default AiSummaryCard
