import React, { useState } from 'react'
import { Tag as TagIcon, Wand2 } from 'lucide-react'
import { suggestTags, TagSuggestion } from '../api/aiApi'
import { applyTag } from '../api/tags'
import { useQueryClient } from '@tanstack/react-query'

interface AiTagsCardProps {
    requestId: number
}

const AiTagsCard: React.FC<AiTagsCardProps> = ({ requestId }) => {
    const [suggestions, setSuggestions] = useState<TagSuggestion[] | null>(null)
    const [isLoading, setIsLoading] = useState(false)
    const [error, setError] = useState<string | null>(null)
    const [metaInfo, setMetaInfo] = useState<string | null>(null)
    const [applyingTag, setApplyingTag] = useState<string | null>(null)
    const [appliedTags, setAppliedTags] = useState<Set<string>>(new Set())

    const queryClient = useQueryClient()

    const handleSuggest = async () => {
        setIsLoading(true)
        setError(null)
        try {
            const data = await suggestTags(requestId)
            setSuggestions(data.tags)
            setMetaInfo(`Generated by ${data.provider} (${data.model}) in ${data.latencyMs}ms`)
        } catch (err: unknown) {
            const message = (err as { response?: { data?: { message?: string } } })?.response?.data?.message
            setError(message || 'Failed to suggest tags.')
        } finally {
            setIsLoading(false)
        }
    }

    const handleApplyTag = async (tag: TagSuggestion) => {
        setApplyingTag(tag.name)
        try {
            await applyTag(requestId, tag.name, tag.isNew)
            queryClient.invalidateQueries({ queryKey: ['request-tags', requestId] })
            setAppliedTags(prev => {
                const updated = new Set(prev)
                updated.add(tag.name)
                return updated
            })
        } catch (err: unknown) {
            const message = err instanceof Error ? err.message : (err as { response?: { data?: { message?: string } } })?.response?.data?.message
            alert(message || 'Failed to apply tag')
        } finally {
            setApplyingTag(null)
        }
    }

    return (
        <div style={{ backgroundColor: 'var(--color-bg)', padding: 16, borderRadius: 6 }}>
            <div className="flex items-center justify-between mb-2">
                <div className="flex items-center gap-2 font-medium text-sm">
                    <TagIcon size={14} color="var(--color-primary)" />
                    Tag Suggestions
                </div>
                {!suggestions && (
                    <button
                        className="btn btn-primary"
                        style={{ padding: '4px 10px', fontSize: 12 }}
                        onClick={handleSuggest}
                        disabled={isLoading}
                    >
                        {isLoading ? 'Suggesting...' : <><Wand2 size={12} /> Generate</>}
                    </button>
                )}
            </div>

            {error && <div className="alert alert-error text-sm" style={{ padding: 8 }}>{error}</div>}

            {suggestions && (
                <div>
                    <div className="flex flex-col gap-2" style={{ marginTop: 12 }}>
                        {suggestions.length === 0 && <p className="text-sm text-muted">No tags suggested.</p>}
                        {suggestions.map((tag, idx) => (
                            <div key={idx} className="flex items-center justify-between" style={{ padding: '8px 12px', backgroundColor: 'white', border: '1px solid var(--color-border)', borderRadius: 4 }}>
                                <div>
                                    <div className="flex items-center gap-2">
                                        <span style={{ fontWeight: 600, fontSize: 13 }}>{tag.name}</span>
                                        {tag.isNew && <span style={{ fontSize: 10, backgroundColor: 'var(--color-primary-light)', color: 'var(--color-primary)', padding: '2px 6px', borderRadius: 10 }}>NEW</span>}
                                    </div>
                                    <div className="text-xs text-muted" style={{ marginTop: 2 }}>{tag.reason}</div>
                                </div>
                                <button
                                    className="btn btn-secondary"
                                    style={{ padding: '4px 8px', fontSize: 11 }}
                                    disabled={applyingTag === tag.name || appliedTags.has(tag.name)}
                                    onClick={() => handleApplyTag(tag)}
                                >
                                    {appliedTags.has(tag.name) ? 'Applied ✓' : (applyingTag === tag.name ? 'Applying...' : (tag.isNew ? 'Create & Apply' : 'Apply Tag'))}
                                </button>
                            </div>
                        ))}
                    </div>

                    <div className="flex items-center justify-between mt-3">
                        <span className="text-muted text-xs">{metaInfo}</span>
                        <button
                            className="btn btn-secondary"
                            style={{ padding: '4px 10px', fontSize: 12 }}
                            onClick={handleSuggest}
                            disabled={isLoading}
                        >
                            {isLoading ? 'Retry...' : 'Regenerate'}
                        </button>
                    </div>
                </div>
            )}
        </div>
    )
}

export default AiTagsCard
