aws_region          = "ap-southeast-2"
environment         = "dev"
github_user         = "JasonYuSun"
github_repo         = "secure-support-hub"
ai_provider         = "bedrock"
ai_bedrock_model_id = "anthropic.claude-sonnet-4-6"
